# Generated by Django 4.2.7 on 2025-05-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
