# Generated by Django 4.2.7 on 2025-05-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_author_event_slug_event_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='client_name',
        ),
    ]
