# Generated by Django 4.2.7 on 2025-09-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='core.service'),
        ),
    ]
